# Generated by Django 6.0.2 on 2026-05-17 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyKeywordLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords_english', models.JSONField(default=list)),
                ('keywords_roman_urdu', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('weather_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='api.weatherrequest')),
            ],
        ),
    ]
