# Generated by Django 6.0.2 on 2026-05-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_anomalykeywordlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherrequest',
            name='aqi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherrequest',
            name='city_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weatherrequest',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
