# Generated by Django 6.0.2 on 2026-05-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_weatherrequest_aqi_weatherrequest_city_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherrequest',
            name='firms_fires_detected',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
