# Generated by Django 6.0.2 on 2026-05-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_weatherrequest_firms_fires_detected'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherrequest',
            name='tomtom_incidents_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='weatherrequest',
            name='tomtom_incidents_summary',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
