# Generated by Django 6.0.2 on 2026-05-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_weatherrequest_tomtom_incidents_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherrequest',
            name='sector',
        ),
    ]
