# Generated by Django 6.0.2 on 2026-05-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_weatherrequest_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCrisisScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crisis_type', models.CharField(choices=[('heatwave', 'Heatwave'), ('fire', 'Fire'), ('road_accident', 'Road Accident'), ('safe_response', 'Safe Response')], max_length=50)),
                ('location', models.CharField(help_text="Enter city name (e.g. Islamabad), or 'all' to apply to all requests.", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Check to activate this simulated scenario.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
