# Generated by Django 6.0.2 on 2026-05-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_admincrisisscenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('incident_type', models.CharField(choices=[('accident', 'Accident'), ('fire', 'Fire'), ('flood', 'Flooding'), ('road_closure', 'Road Closure'), ('power_outage', 'Power Outage'), ('gas_leak', 'Gas Leak'), ('protest', 'Protest'), ('crime', 'Crime'), ('medical', 'Medical Emergency'), ('other', 'Other')], default='other', max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius_km', models.FloatField(default=1.0, help_text='Affected area radius in km')),
                ('custom_boundary', models.JSONField(blank=True, help_text='Custom polygon points if user drew a shape', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
