# Generated by Django 6.0.2 on 2026-05-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_communityincident'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincrisisscenario',
            name='custom_ai_response',
            field=models.JSONField(blank=True, help_text='Custom AI JSON response for this scenario.', null=True),
        ),
        migrations.AddField(
            model_name='admincrisisscenario',
            name='custom_search_results',
            field=models.JSONField(blank=True, help_text='Custom Search results for this scenario.', null=True),
        ),
        migrations.AlterField(
            model_name='admincrisisscenario',
            name='crisis_type',
            field=models.CharField(choices=[('heatwave', 'Heatwave'), ('fire', 'Fire'), ('road_accident', 'Road Accident'), ('mandi_bahauddin_fire', 'Mandi Bahauddin Fire (Static)'), ('safe_response', 'Safe Response')], max_length=50),
        ),
    ]
