# Generated by Django 6.0.2 on 2026-05-17 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('user_time', models.DateTimeField(blank=True, null=True)),
                ('temperature_2m', models.FloatField(blank=True, null=True)),
                ('relative_humidity_2m', models.FloatField(blank=True, null=True)),
                ('apparent_temperature', models.FloatField(blank=True, null=True)),
                ('is_day', models.IntegerField(blank=True, null=True)),
                ('precipitation', models.FloatField(blank=True, null=True)),
                ('rain', models.FloatField(blank=True, null=True)),
                ('showers', models.FloatField(blank=True, null=True)),
                ('snowfall', models.FloatField(blank=True, null=True)),
                ('weather_code', models.IntegerField(blank=True, null=True)),
                ('cloud_cover', models.FloatField(blank=True, null=True)),
                ('pressure_msl', models.FloatField(blank=True, null=True)),
                ('surface_pressure', models.FloatField(blank=True, null=True)),
                ('wind_speed_10m', models.FloatField(blank=True, null=True)),
                ('wind_direction_10m', models.FloatField(blank=True, null=True)),
                ('wind_gusts_10m', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('query', models.CharField(max_length=255)),
                ('results', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('weather_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='api.weatherrequest')),
            ],
        ),
        migrations.CreateModel(
            name='AIResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('response_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('weather_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_responses', to='api.weatherrequest')),
            ],
        ),
    ]
